### ISSUE TITLE
Needs proxy support

### ISSUE THREAD

**Issue by MrARM** [nelsonfigueroa/jackboxtv-room-finder#2]
I gave the script a spin, but I got IP banned within a minute, it's an awesome concept, however if you really want to troll people, you'll need some kind of way to evade the blocker.

**Comment by 123coven** [comment]
the old version used to work but then it gave me an error so i tried to newer version and go ip blocked

**Comment by nelsonfigueroa** [comment]
Yeah there's some sort of throttling going on. Haven't figured out a way around it.
